import http from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,createHmac,timingSafeEqual,createSign,createHash,createPublicKey,verify} from 'node:crypto';
import {demo,normalize,todayHK} from '../shared/model.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');try{const envTxt=await readFile(path.join(root,'.env'),'utf8');for(const line of envTxt.split('\n')){const t=line.trim();if(!t||t.startsWith('#'))continue;const eq=t.indexOf('=');if(eq===-1)continue;const k=t.slice(0,eq).trim();let v=t.slice(eq+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[k]=v;}}catch(e){if(e.code!=='ENOENT')throw e}
const E=process.env,mode=E.APP_MODE||'demo',live=mode==='live',port=Number(E.PORT||3000),origin=E.APP_ORIGIN||`http://localhost:${port}`,u=new URL(origin),secure=u.protocol==='https:';
if(!['demo','live'].includes(mode))throw Error('Invalid APP_MODE');if(u.origin!==origin)throw Error('APP_ORIGIN must be origin only, with no trailing slash');if(!secure&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error('HTTPS required for public deployments');
if(live){for(const k of ['ALLOWED_EMAIL','GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_SERVICE_ACCOUNT_EMAIL','GOOGLE_PRIVATE_KEY','PERSONAL_SPREADSHEET_ID','FAMILY_SPREADSHEET_ID','PERSONAL_RANGE','FAMILY_RANGE'])if(!E[k])throw Error('Missing configuration: '+k);if(E.SESSION_SECRET&&E.SESSION_SECRET.length<32)throw Error('SESSION_SECRET must have at least 32 random characters');if(E.CURRENCY_CONFIRMED!=='HKD')throw Error('Verify both sources use HKD, then set CURRENCY_CONFIRMED=HKD');}
const secret=E.SESSION_SECRET||randomBytes(48).toString('hex'),SESSION='lens_session',FLOW='lens_oauth';
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors *; base-uri 'self'; form-action 'self'"};if(secure)headers['Strict-Transport-Security']='max-age=31536000';
const enc=o=>Buffer.from(JSON.stringify(o)).toString('base64url');
const seal=o=>{const b=enc(o);return b+'.'+createHmac('sha256',secret).update(b).digest('base64url')};
function unseal(t){try{const [b,s]=t.split('.'),a=createHmac('sha256',secret).update(b).digest(),z=Buffer.from(s,'base64url');if(a.length!==z.length||!timingSafeEqual(a,z))return null;const o=JSON.parse(Buffer.from(b,'base64url'));return o.exp>Date.now()/1000?o:null}catch{return null}}
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim().split(/=(.*)/s).slice(0,2)));
const cookie=(name,val,age,isSec=secure)=>`${name}=${val}; Path=/; HttpOnly; ${isSec?'SameSite=None; Secure; Partitioned':'SameSite=Lax'}; Max-Age=${age}`;
const send=(res,status,body,h={})=>{res.writeHead(status,{...headers,...h});res.end(body)};
const json=(res,status,body)=>send(res,status,JSON.stringify(body),{'Content-Type':'application/json'});
const redirect=(res,url,c)=>send(res,302,'',{Location:url,...(c?{'Set-Cookie':c}:{})});
async function getJSON(url,opts={}){const r=await fetch(url,{...opts,signal:AbortSignal.timeout(20000)});if(!r.ok){const e=Error('Upstream request failed');e.status=r.status;throw e}return r.json()}
const tokenEndpoint='https://'+'oauth2.googleapis.com/token';
let keys=null;
function formatPrivateKey(raw){if(!raw)return '';let k=String(raw).trim();try{const j=JSON.parse(k);if(j.private_key)k=j.private_key;}catch{}k=k.replace(/\\n/g,'\n').trim();if(!k.includes('BEGIN PRIVATE KEY')){k='-----BEGIN PRIVATE KEY-----\n'+k+'\n-----END PRIVATE KEY-----';}return k;}
async function identity(token,nonce){const a=token.split('.');if(a.length!==3)throw Error('Invalid token');const h=JSON.parse(Buffer.from(a[0],'base64url'));if(h.alg!=='RS256')throw Error('Invalid algorithm');if(!keys||keys.until<Date.now())keys={...await getJSON('https://'+'www.googleapis.com/oauth2/v3/certs'),until:Date.now()+3600000};const key=keys.keys.find(k=>k.kid===h.kid);if(!key){keys=null;throw Error('Retry sign in')}if(!verify('RSA-SHA256',Buffer.from(a[0]+'.'+a[1]),createPublicKey({key,format:'jwk'}),Buffer.from(a[2],'base64url')))throw Error('Invalid signature');const p=JSON.parse(Buffer.from(a[1],'base64url')),now=Date.now()/1000;if(!['accounts.google.com','https://accounts.google.com'].includes(p.iss)||p.aud!==E.GOOGLE_CLIENT_ID||p.exp<=now||p.iat>now+60||p.nonce!==nonce||p.email_verified!==true||!p.sub||p.email?.toLowerCase()!==E.ALLOWED_EMAIL.toLowerCase())throw Error('Unauthorized identity');return p}
let token=null;
async function serviceToken(){if(token&&token.until>Date.now()+60000)return token.value;const now=Math.floor(Date.now()/1000),body=enc({alg:'RS256',typ:'JWT'})+'.'+enc({iss:E.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:tokenEndpoint,iat:now,exp:now+3600}),sig=createSign('RSA-SHA256').update(body).sign(formatPrivateKey(E.GOOGLE_PRIVATE_KEY),'base64url');const r=await getJSON(tokenEndpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:body+'.'+sig})});token={value:r.access_token,until:Date.now()+r.expires_in*1000};return token.value}
const mapping=E.CATEGORY_MAP_JSON?JSON.parse(E.CATEGORY_MAP_JSON):{};for(const source of ['Personal','Family'])for(const v of Object.values(mapping[source]||{}))if(typeof v!=='string')throw Error('Category mapping values must be strings');
const cache=new Map(),pending=new Map();
async function readSource(source,force){const old=cache.get(source);if(old&&Date.now()-old.at<(force?5000:20000))return old;if(pending.has(source))return pending.get(source);const job=(async()=>{try{const pre=source.toUpperCase(),base='https://'+'sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(E[pre+'_SPREADSHEET_ID']),auth={Authorization:'Bearer '+await serviceToken()};const meta=await getJSON(base+'?fields=properties(timeZone)',{headers:auth});if(!['Asia/Hong_Kong','Asia/Shanghai'].includes(meta.properties.timeZone))throw Error('Spreadsheet timezone must be Asia/Hong_Kong or Asia/Shanghai. Verify its settings.');const result=await getJSON(base+'/values/'+encodeURIComponent(E[pre+'_RANGE'])+'?valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER',{headers:auth});const d=normalize(result.values,source,mapping[source]||{}),s={rows:d.rows,status:{source,status:'ok',lastSuccess:new Date().toISOString(),errors:d.errors,warnings:d.warnings,count:d.rows.length},at:Date.now()};cache.set(source,s);return s}catch(e){const known=/^(Missing header|Duplicate headers|Spreadsheet timezone)/.test(e.message);const message=known?e.message:e.status===403||e.status===404?'Check source ID, range and service-account Viewer access.':e.status===429?'Google quota reached; retrying shortly.':'Source read failed. Check credentials, range and network.';const s={rows:old?.rows||[],status:{source,status:old?.status.lastSuccess?'stale':'unavailable',lastSuccess:old?.status.lastSuccess||null,errors:old?.status.errors||[],warnings:old?.status.warnings||0,count:old?.rows.length||0,message},at:Date.now()};cache.set(source,s);return s}finally{pending.delete(source)}})();pending.set(source,job);return job}
function form(v){try{const u=new URL(v);return u.protocol==='https:'&&['forms.gle','docs.google.com'].includes(u.hostname)?v:null}catch{return null}}
const server=http.createServer(async(req,res)=>{try{const forwardedProto=(req.headers['x-forwarded-proto']||'').split(',')[0].trim();const forwardedHost=(req.headers['x-forwarded-host']||'').split(',')[0].trim();const currentOrigin=forwardedHost?`${forwardedProto||'https'}://${forwardedHost}`:origin;const isSec=forwardedProto==='https'||secure;const url=new URL(req.url,currentOrigin),route=url.pathname;if(req.method!=='GET'&&!(route==='/auth/logout'&&req.method==='POST'))return json(res,405,{error:'Method not allowed'});
if(route==='/health')return json(res,200,{ok:true,mode});
if(route==='/auth/google'){if(!live)return redirect(res,'/');const verifier=randomBytes(48).toString('base64url'),nonce=randomBytes(24).toString('base64url'),flowData={verifier,nonce,exp:Date.now()/1000+600},state=seal(flowData),params=new URLSearchParams({client_id:E.GOOGLE_CLIENT_ID,redirect_uri:currentOrigin+'/auth/callback',response_type:'code',scope:'openid email',state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',prompt:'select_account'});return redirect(res,'https://'+'accounts.google.com/o/oauth2/v2/auth?'+params,cookie(FLOW,state,600,isSec))}
if(route==='/auth/callback'){if(!live)return redirect(res,'/');const stateParam=url.searchParams.get('state')||'',code=url.searchParams.get('code')||'';let flow=unseal(stateParam);if(!flow)flow=unseal(cookies(req)[FLOW]||'');if(!flow||!flow.verifier||!code)return send(res,400,'Sign-in could not be verified. Return to the app and retry.',{'Content-Type':'text/plain','Set-Cookie':cookie(FLOW,'',0,isSec)});try{const result=await getJSON(tokenEndpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:E.GOOGLE_CLIENT_ID,client_secret:E.GOOGLE_CLIENT_SECRET,redirect_uri:currentOrigin+'/auth/callback',grant_type:'authorization_code',code_verifier:flow.verifier})}),p=await identity(result.id_token,flow.nonce);const page=`<!doctype html><html><body style="font-family:system-ui,-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#f8fafc;color:#1e293b"><div style="text-align:center"><h2 style="margin-bottom:8px">Signed in successfully</h2><p style="color:#64748b">Returning to dashboard…</p></div><script>if(window.opener){try{window.opener.postMessage({type:'OAUTH_AUTH_SUCCESS'},'*');}catch(e){}window.close();}else{window.location.href='/';}</script></body></html>`;return send(res,200,page,{'Content-Type':'text/html; charset=utf-8','Set-Cookie':[cookie(FLOW,'',0,isSec),cookie(SESSION,seal({sub:p.sub,email:p.email.toLowerCase(),exp:Date.now()/1000+28800}),28800,isSec)]})}catch(err){return send(res,403,'Sign-in not authorized. Return to the app and use the approved Google account.',{'Content-Type':'text/plain','Set-Cookie':cookie(FLOW,'',0,isSec)})}}
if(route==='/auth/logout'){if(req.method!=='POST'||(req.headers.origin!==origin&&req.headers.origin!==currentOrigin))return json(res,403,{error:'Request denied'});return send(res,204,'',{'Set-Cookie':cookie(SESSION,'',0,isSec)})}
if(route==='/api/expenses'){if(live){const s=unseal(cookies(req)[SESSION]||'');if(!s||!s.sub||s.email!==E.ALLOWED_EMAIL.toLowerCase())return json(res,401,{error:'Sign-in required'});const state=await Promise.all(['Personal','Family'].map(s=>readSource(s,url.searchParams.get('refresh')==='1')));return json(res,200,{mode:'live',today:todayHK(),rows:state.flatMap(s=>s.rows),statuses:state.map(s=>s.status),forms:{Personal:form(E.PERSONAL_FORM_URL),Family:form(E.FAMILY_FORM_URL)}})}return json(res,200,demo())}
const target=route==='/'?'index.html':decodeURIComponent(route).replace(/^\//,'');if(!/^(index\.html|assets\/[a-zA-Z0-9._-]+)$/.test(target))return send(res,404,'Not found');try{const body=await readFile(path.join(root,'dist',target)),ext=path.extname(target);return send(res,200,body,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':'application/octet-stream'})}catch{return send(res,404,'Build files missing. Run npm run build.')}}catch{return json(res,500,{error:'Service unavailable. No data was changed.'})}});
server.listen(port,'0.0.0.0',()=>console.log(`Expense Lens listening on ${port} (${mode} mode).`));
