export const pad=n=>String(n).padStart(2,'0');
export const todayHK=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const shift=(m,n)=>{const [y,a]=m.split('-').map(Number),d=new Date(Date.UTC(y,a-1+n,1));return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}`};
export const days=m=>{const [y,a]=m.split('-').map(Number);return new Date(Date.UTC(y,a,0)).getUTCDate()};
export const dayShift=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const sum=ts=>ts.reduce((a,t)=>a+t.amount,0);
export const range=(ts,a,b)=>ts.filter(t=>t.day>=a&&t.day<=b);
export const scoped=(ts,s,p='Everyone')=>ts.filter(t=>(s==='Combined'||t.source===s)&&(s!=='Family'||p==='Everyone'||t.payer===p));
export function period(m,today,full=false){const current=m===today.slice(0,7),prev=shift(m,-1),d=current&&!full?+today.slice(8):days(m);return {start:m+'-01',end:m+'-'+pad(d),prevStart:prev+'-01',prevEnd:prev+'-'+pad(current&&!full?Math.min(d,days(prev)):days(prev)),aligned:current&&!full};}
export function difference(a,b){if(a<0||b<0)return 'Signed adjustment';if(b===0)return a>0?'New spending':'No change';const n=(a-b)/b*100;return `${n>0?'+':''}${n.toFixed(1)}%`;}
export function cents(v){const s=String(v).trim();if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw Error('Invalid amount (numeric, max 2 decimals)');const [a,b='']=s.replace('-','').split('.'),n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw Error('Amount outside safe range');return s.startsWith('-')?-n:n;}
export function timestamp(v){if(typeof v==='number'){if(!Number.isFinite(v)||v<=0||v>2958465)throw Error('Invalid date serial');const d=new Date(Date.UTC(1899,11,30)+Math.round(v*86400)*1000);v=`${pad(d.getUTCDate())}/${pad(d.getUTCMonth()+1)}/${d.getUTCFullYear()} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`;}const m=String(v).trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?: (\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(!m)throw Error('Invalid date; expected DD/MM/YYYY HH:mm:ss');const [,dd,mm,yy,hh='0',mi='0',ss='0']=m;const [d,mo,y,h,min,s]=[dd,mm,yy,hh,mi,ss].map(Number);const check=new Date(Date.UTC(y,mo-1,d));if(check.getUTCDate()!==d||check.getUTCMonth()!==mo-1||check.getUTCFullYear()!==y||h>23||min>59||s>59)throw Error('Invalid calendar date/time');const day=`${yy}-${pad(mo)}-${pad(d)}`,time=`${pad(h)}:${pad(min)}`;return {day,time,at:new Date(`${day}T${time}:${pad(s)}+08:00`).toISOString()};}
export function normalize(values,source,map={}){if(!values?.length)throw Error('Missing header row');const h=values[0].map(x=>String(x).trim());for(const f of ['Timestamp','Category','Amount',...(source==='Family'?['Pay by']:[])])if(!h.includes(f))throw Error('Missing header: '+f);if(new Set(h.filter(Boolean)).size!==h.filter(Boolean).length)throw Error('Duplicate headers');const rows=[],errors=[];let warnings=0;values.slice(1).forEach((r,i)=>{if(r.every(v=>v===''||v==null))return;const get=k=>r[h.indexOf(k)]??'';try{const original=String(get('Category')).trim()||'Uncategorized';const t={id:source+':'+(i+2),source,...timestamp(get('Timestamp')),amount:cents(get('Amount')),original,category:map[original]||original,payer:source==='Family'?(String(get('Pay by')).trim()||'Unknown'):null,remarks:String(get('Remarks'))};rows.push(t);if(original==='Uncategorized')warnings++;}catch(e){errors.push({row:i+2,reason:e.message})}});return {rows,errors,warnings};}
const median=ns=>{const a=[...ns].sort((x,y)=>x-y),i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
export function signals(rows,p,scope,payer='Everyone'){const output=[];for(const source of scope==='Combined'?['Personal','Family']:[scope]){const all=scoped(rows,source,payer),current=range(all,p.start,p.end),earliest=all.map(t=>t.day).sort()[0];for(const cat of new Set(current.map(t=>t.original))){const group=all.filter(t=>t.original===cat),sel=current.filter(t=>t.original===cat),backs=[1,2,3].map(n=>{const m=shift(p.start.slice(0,7),-n);return [m+'-01',m+'-'+pad(p.aligned?Math.min(+p.end.slice(8),days(m)):days(m))]});const baseline=median(backs.map(([a,b])=>sum(range(group,a,b)))),actual=sum(sel);if(earliest&&earliest<=backs[2][0]&&baseline>0&&actual>=baseline*1.3&&actual-baseline>=30000)output.push({id:`cat-${source}-${cat}`,type:'Category change',title:`${cat} is higher than usual`,source,amount:actual,baseline,delta:actual-baseline,reason:'At least 30% and HK$300 above the median of three comparable monthly periods. Signed entries included.',dates:backs.map(b=>b.join(' → ')).join('; '),ids:sel.map(t=>t.id)});
for(const t of sel.filter(t=>t.amount>0)){const m=shift(t.day.slice(0,7),-6),from=m+'-'+pad(Math.min(+t.day.slice(8),days(m))),history=group.filter(x=>x.at<t.at&&x.day>=from&&x.amount>0);if(history.length>=20){const b=median(history.map(x=>x.amount));if(t.amount>b*3&&t.amount-b>30000)output.push({id:'large-'+t.id,type:'Large entry',title:`A larger ${cat.toLowerCase()} entry`,source,amount:t.amount,baseline:b,delta:t.amount-b,reason:`Over 3× the median and HK$300 above it, based on ${history.length} earlier positive entries in this source/category.`,dates:from+' → before '+t.day+' '+t.time,ids:[t.id]});}}}
const seen=new Map();for(const t of [...all].sort((a,b)=>a.at.localeCompare(b.at))){const key=JSON.stringify([t.original,t.amount,t.payer]),b=seen.get(key);if(b&&Date.parse(t.at)-Date.parse(b.at)<=600000&&(t.day>=p.start&&t.day<=p.end||b.day>=p.start&&b.day<=p.end))output.push({id:`dup-${b.id}-${t.id}`,type:'Similar entries',title:`Check similar ${t.original.toLowerCase()} entries`,source,amount:t.amount,baseline:null,delta:0,reason:'Same source, category, amount and payer within ten minutes. Batch entry may explain this; nothing is excluded.',dates:b.day+' '+b.time+' → '+t.day+' '+t.time,ids:[b.id,t.id]});seen.set(key,t);}}
return output.sort((a,b)=>b.delta-a.delta);}
export function demo(){let seed=731,id=0;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const rows=[];const add=(source,day,category,amount,remarks,payer=null,time='12:35')=>rows.push({id:'demo-'+(++id),source,day,time,at:new Date(day+'T'+time+':00+08:00').toISOString(),category,original:category,amount:Math.round(amount*100),remarks,payer});for(let back=7;back>=0;back--){const m=shift('2026-09',-back);for(let d=1;d<=(back===0?10:days(m));d++){const day=m+'-'+pad(d);if(back===0&&d===8)continue;add('Personal',day,'Meal',32+Math.round(random()*66),'Lunch near the office');if(d%3!==0)add('Personal',day,'Transportation',14+Math.round(random()*28),'MTR & bus',null,'08:42');if(d%5===0)add('Personal',day,'Entertainment',80+Math.round(random()*170),'Basketball / gathering',null,'20:10');if(d===2)add('Personal',day,'Subscription',178,'Monthly subscriptions',null,'09:20');if(d%3===1)add('Family',day,'Groceries',160+Math.round(random()*220),'Weekly groceries',d%2?'Karen':'Derek','19:24');if(d%4===0)add('Family',day,'Meal',120+Math.round(random()*300),'Family dinner',d%3?'Karen':'Derek','20:15');if(d%6===0)add('Family',day,'Taxi/Uber',72+Math.round(random()*90),'Ride home','Karen','22:08');if(d===3)add('Family',day,'Household',285,'Cleaning supplies','Derek','18:40');}}add('Personal','2026-09-09','Entertainment',780,'Concert tickets',null,'21:04');add('Family','2026-09-06','Groceries',920,'Monthly pantry restock','Karen','17:18');add('Personal','2026-09-07','Entertainment',-120,'Returned booking',null,'15:40');add('Family','2026-09-05','Taxi/Uber',133,'Ride home','Karen','21:51');add('Family','2026-09-05','Taxi/Uber',133,'Ride home','Karen','21:55');return {mode:'demo',today:'2026-09-10',rows,statuses:['Personal','Family'].map(source=>({source,status:'ok',lastSuccess:new Date().toISOString(),errors:[],warnings:0,count:rows.filter(t=>t.source===source).length})),forms:{Personal:'https://forms.gle/KQuSFhzTKtXgf98k8',Family:null}};}
